create table if not exists public.wishes (
  id bigint generated by default as identity primary key,
  text text not null,
  done boolean not null default false,
  author_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.places (
  id bigint generated by default as identity primary key,
  title text not null,
  note text,
  event_at timestamptz not null,
  author_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  place_name text not null,
  rating integer not null check (rating between 1 and 10),
  comment text,
  author_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.moments (
  id bigint generated by default as identity primary key,
  title text not null,
  text text not null,
  happened_at timestamptz not null,
  author_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.friends_meetings (
  id bigint generated by default as identity primary key,
  friends_name text not null,
  note text,
  happened_at timestamptz not null,
  author_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.date_ideas (
  id bigint generated by default as identity primary key,
  title text not null,
  text text,
  author_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.quotes (
  id bigint generated by default as identity primary key,
  text text not null,
  author_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.gratitude (
  id bigint generated by default as identity primary key,
  text text not null,
  author_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  created_at timestamptz not null default now()
);

alter table public.wishes enable row level security;
alter table public.places enable row level security;
alter table public.reviews enable row level security;
alter table public.moments enable row level security;
alter table public.friends_meetings enable row level security;
alter table public.date_ideas enable row level security;
alter table public.quotes enable row level security;
alter table public.gratitude enable row level security;

-- Просмотр доступен без входа.
create policy "public read wishes" on public.wishes for select using (true);
create policy "public read places" on public.places for select using (true);
create policy "public read reviews" on public.reviews for select using (true);
create policy "public read moments" on public.moments for select using (true);
create policy "public read friends" on public.friends_meetings for select using (true);
create policy "public read dates" on public.date_ideas for select using (true);
create policy "public read quotes" on public.quotes for select using (true);
create policy "public read gratitude" on public.gratitude for select using (true);

-- Добавление/изменение/удаление — только после Supabase-входа.
create policy "auth insert wishes" on public.wishes for insert to authenticated with check (author_id = auth.uid());
create policy "auth update wishes" on public.wishes for update to authenticated using (true) with check (true);
create policy "auth delete wishes" on public.wishes for delete to authenticated using (true);

create policy "auth insert places" on public.places for insert to authenticated with check (author_id = auth.uid());
create policy "auth update places" on public.places for update to authenticated using (true) with check (true);
create policy "auth delete places" on public.places for delete to authenticated using (true);

create policy "auth insert reviews" on public.reviews for insert to authenticated with check (author_id = auth.uid());
create policy "auth update reviews" on public.reviews for update to authenticated using (true) with check (true);
create policy "auth delete reviews" on public.reviews for delete to authenticated using (true);

create policy "auth insert moments" on public.moments for insert to authenticated with check (author_id = auth.uid());
create policy "auth update moments" on public.moments for update to authenticated using (true) with check (true);
create policy "auth delete moments" on public.moments for delete to authenticated using (true);

create policy "auth insert friends" on public.friends_meetings for insert to authenticated with check (author_id = auth.uid());
create policy "auth update friends" on public.friends_meetings for update to authenticated using (true) with check (true);
create policy "auth delete friends" on public.friends_meetings for delete to authenticated using (true);

create policy "auth insert dates" on public.date_ideas for insert to authenticated with check (author_id = auth.uid());
create policy "auth update dates" on public.date_ideas for update to authenticated using (true) with check (true);
create policy "auth delete dates" on public.date_ideas for delete to authenticated using (true);

create policy "auth insert quotes" on public.quotes for insert to authenticated with check (author_id = auth.uid());
create policy "auth update quotes" on public.quotes for update to authenticated using (true) with check (true);
create policy "auth delete quotes" on public.quotes for delete to authenticated using (true);

create policy "auth insert gratitude" on public.gratitude for insert to authenticated with check (author_id = auth.uid());
create policy "auth update gratitude" on public.gratitude for update to authenticated using (true) with check (true);
create policy "auth delete gratitude" on public.gratitude for delete to authenticated using (true);

-- Для старых версий Supabase/Data API:
grant select on all tables in schema public to anon;
grant select, insert, update, delete on all tables in schema public to authenticated;
